config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  resources :messages

  root to: 'messages#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :messages

  validates_presence_of :phone_number, :name
end

app/models/message.rb
class Message < ActiveRecord::Base
  # before_create :send_message
  has_and_belongs_to_many :contacts



  # private

  def send_message(message)
    begin
      response = RestClient::Request.new(
      :method => :post,
      :url => 'https://api.twilio.com/2010-04-01/Accounts/AC2a025b06ca2aa65b4dc2cd1abbbd78c6/Messages.json',
      :user => 'AC2a025b06ca2aa65b4dc2cd1abbbd78c6',
      :password => '925053a11eef433c0f37db0e1eb77dda',
      :payload => { :Body => message.body,
                    :To => message.to,
                    :From => message.from }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :contacts

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all.order(name: :desc)
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create

    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @contact.update(contact_params)
      redirect_to @contact
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to root_path
  end


private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:user_id, :phone_number, :name)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, except: [:new, :create, :index]

  def new
    @message = Message.new
    @contacts = Contact.all
  end

  def create

    @contacts = Contact.all
    @message = Message.new(message_params)

    params[:contact_phone_numbers].each do |contact|
      msg = Message.create!(to: contact, from: @message.from, body: @message.body)
      msg.send_message(msg)
    end

    if @message.save
      redirect_to messages_path
    else
      render :new
    end
  end

  def index
    @messages = Message.all
  end

  def show
  end

  def destroy
    @message.destroy
    redirect_to messages_path
  end



private

  def find_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:to, :from, :body, contact_phone_numbers: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<% if @contacts.any? %>
  <table>
    <tr>
      <td></td>
      <td>Name</td>
      <td>Number</td>
    </tr>
    <% @contacts.each_with_index do |contact, index| %>
      <tr>
        <%= link_to contact_path(contact) do %>
          <td><%= index + 1 %></td>
          <td><%= contact.name %></td>
          <td><%= contact.phone_number %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/contacts/new.html.erb
<%= form_for @contact do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.submit %>
<% end %>

app/views/contacts/show.html.erb
<h3>Name</h3>
<%= @contact.name %>
<h3>Number</h3>
<%= @contact.phone_number %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Texter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/index.html.erb
  <ul>
    <% @messages.each do |message| %>
      <li><%= message.id %></li>
    <% end %>
  </ul>

<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<%= form_for @message do |f| %>
  <%= f.label :to %>


  <% Contact.all.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= check_box_tag "contact_phone_numbers[]", contact.phone_number %></td>
  </tr>
  <% end %>

  <%= f.label :from %>
  <%= f.text_field :from %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

<%= link_to "New Contact", new_contact_path %>